eccmerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('produtos/', include('produtos.urls'))
]

home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('cadastro/', views.Cadastro.as_view(), name='cadastro')
]

produtos/urls.py
from django.urls import path
from . import views
app_name = 'produtos'
urlpatterns = [
    path('', views.Produtos.as_view(), name='homepage'),
    path('<prod_codigo>',views.comprar.as_view(), name='detalhe')
]

home/models.py
from django.db import models

produtos/models.py
from django.db import models
from django.contrib.auth.models import User
class CategoriaModels(models.Model):
    cate_codigo = models.BigAutoField(primary_key=True)
    cate_nome = models.CharField(max_length=80)

    def __str__(self):
        return self.cate_nome
class ProdutosModels(models.Model):
    prod_codigo = models.BigAutoField(primary_key=True)
    prod_nome = models.CharField(max_length=80, verbose_name='Nome')
    prod_categoria = models.ForeignKey(CategoriaModels, on_delete=models.CASCADE, verbose_name='Categoria')
    prod_estoque = models.IntegerField(max_length=200, verbose_name='Estoque')
    prod_preco = models.FloatField(max_length=20, verbose_name='Preço')
    def __str__(self):
        return self.prod_nome
class CompraModels(models.Model):
    comp_codigo = models.BigAutoField(primary_key=True)
    comp_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True,blank=True)
    comp_produto = models.ForeignKey(ProdutosModels, on_delete=models.CASCADE, null=True,blank=True)
    comp_quantidade = models.IntegerField(null=True,blank=True)

home/forms.py
from django import forms
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label='Senha'
    )
    class Meta:
        model = User
        fields = ('username','password','email')

produtos/forms.py
from django import forms
from . import models
class Comprar(forms.ModelForm):
    class Meta:
        model = models.CompraModels
        fields = '__all__'
class Produto(forms.ModelForm):
    class Meta:
        model = models.ProdutosModels
        fields = '__all__'

home/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.contrib.auth import login,authenticate
from . import forms

class Home(View):
    template_name = 'home/index.html'
    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)

        self.formulario = {
            'user': forms.UserForm(
                data=self.request.POST or None,

            )
        }
        self.usuarioFormulario = self.formulario['user']
    def get(self, *args, **kwargs):
        return render(self.request, self.template_name, self.formulario)
class Login(Home):
    def post(self, *args, **kwargs):
        usuario = self.request.POST.get('username')
        senha = self.request.POST.get('password')

        if not usuario or not senha:
            print('Erro 1')
            return redirect('home:login')
        usuario = authenticate(
            self.request, username=usuario, password=senha)

        if not usuario:
            print('Erro 2')
            return redirect('home:login')

        login(self.request, user=usuario)
        print('certo')
        return redirect('produtos:homepage')
class Cadastro(Home):
    template_name = 'home/cadastro.html'
    def get(self, *args, **kwargs):
        return render(self.request, self.template_name, self.formulario)
    def post(self, *args, **kwargs):
        if not self.usuarioFormulario.is_valid():
            return render(self.request, self.template_name, self.formulario)
        senha = self.request.POST.get('password')
        username = self.usuarioFormulario.save(commit=False)
        username.set_password(senha)
        username.save()
        template_name = 'home/index.html'
        return render(self.request, template_name, self.formulario)

produtos/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.models import User
from . import models
from . import forms

class Produtos(ListView):
    model = models.ProdutosModels
    template_name = 'produtos/homepage.html'
    context_object_name = 'Produtos'
class Detalhe(DetailView):
    template_name = 'produtos/detalhe.html'
    pk_url_kwarg = 'prod_codigo'

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)
        prod_codigo = self.kwargs.get('prod_codigo')
        self.produto_banco = get_object_or_404(models.ProdutosModels, prod_codigo=prod_codigo)

        self.comprarForms = {
            'compra':forms.Comprar(data=self.request.POST or None),
            'produto':self.produto_banco,
            'produto_banco': forms.Produto(data=self.request.POST or None),
            'usuario': User
        }
        self.comprar = self.comprarForms['compra']
        self.produto = self.comprarForms['produto_banco']
    def get(self, *args, **kwargs):
        return render(self.request, self.template_name, self.comprarForms)
class comprar(Detalhe):


    def post(self,*args,**kwargs):
        usuario = get_object_or_404(User, username=self.request.user.username)
        comprar_quantidade = self.request.POST.get('comp_quantidade')
        comprar_banco = self.comprar.save(commit=False)
        comprar_banco.comp_user = usuario
        comprar_banco.comp_produto = self.produto_banco
        comprar_banco.save()

        estoque = self.produto_banco.prod_estoque
        estoque -= int(comprar_quantidade)

        self.produto_banco.prod_estoque -= int(comprar_quantidade)
        self.produto_banco.save()



        return render(self.request, self.template_name, self.comprarForms)

home/templates/home/cadastro.html
{% extends 'base.html'%}
{% load static %}
{% block 'body'%}
<main>
    <register>
        <div><!-- style="Margin-top: 120px" -->
            <div style="display: flex; justify-content: center;">
                <h1 style="margin-bottom: 10px; Color: #ffffff; font-size: 30px "> Register </h1>
            </div>
            <div class="gradiente"></div>

            <form action="" method="POST">

                {% csrf_token %}
                <div class="RegisBox">
                    <div class="TextoInput">
                        <h4 style="color: white">Usuario</h4>
                       {{ user.username }}
                        <hr>

                    </div>

                    <div class="TextoInput">
                        <h4 style="color: white">Email</h4>
                        {{ user.email }}
                        <hr>
                    </div>

                    <div class="TextoInput">
                        <h4 style="color: white">Senha</h4>
                        {{ user.password }}
                        <hr>
                    </div>



                    <div class="TextoInput">
                        <h4 style="color: white">Confirmar senha</h4>
                        <input type="password" name="" id="" placeholder="">
                        <hr>
                    </div>
                </div>

                <div class="ButtonRegister">
                    <input class="SignButton" type="Submit" value="Sign Up">
                </div>
            </form>
        </div>
    </register>

    <video autoplay muted loop class="back_video">
        <source src="/video/winter-river-campfire-snowfall-4k-live-wallpaper.mp4" type="video/mp4">
    </video>
</main>

{% endblock%}

home/templates/home/index.html
{% extends 'base.html'%}
{% load static %}
{% block 'body'%}
<main>
    <Login>
        <div style="Margin-top: 120px">
            <div style="display: flex; justify-content: center;">
                <h1 style="margin-bottom: 10px; Color: #ffffff; font-size: 30px "> Login </h1>
            </div>
            <div class="gradiente"></div>

                    <form action="" method="POST">

                        {% csrf_token %}
                <div class="InputLogin">
                    <div class="TextoInput">
                        <h4 style="color: white">Usuário</h4>
                        {{ user.username }}
                        <hr>
                    </div>

                    <div class="TextoInput">
                       <h4 style="color: white">Senha</h4>
                        {{user.password}}
                        <hr>
                    </div>
                </div>

                <div class="ManterLogin">
                    <input type="checkbox" name="" id="CB">
                    <label for="CB"></label>
                    <p> Manter Login </p>
                </div>

                <div class="ButtonLogin">
                    <input class="SignButton" type="Submit" value="Sign Up">
                    <input class="LoginButton" type="Submit" value="Login in">
                </div>
            </form>


        </div>
    </Login>

    <video autoplay muted loop class="back_video">
        <source src="{% static 'lofi-japanese-style-room-day-time-HD-live-wallpaper.mp4' %}" type="video/mp4">
    </video>
</main>

{% endblock%}

produtos/templates/produtos/detalhe.html
{% extends 'base.html' %}
{% block 'body'%}

        <h1>{{produto.prod_nome}}</h1>


<form action="" method="POST">
       {% csrf_token %}
        {{compra.comp_quantidade}}
         <input class="SignButton" type="Submit" value="Compra">
</form>
{%endblock%}

produtos/templates/produtos/homepage.html
{% extends 'base.html' %}
{% block 'body'%}
    {% for produto in Produtos%}
         <a href="{% url 'produtos:detalhe' produto.prod_codigo%}">{{produto.prod_nome}}</a>
    {%endfor%}
{%endblock%}

templates/base.html
{% load static %}
<!doctype html>
<html lang="pt-BR">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> GESTÃO </title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bai+Jamjuree:wght@300&family=Nunito+Sans:wght@300&family=Source+Sans+Pro:wght@300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bai+Jamjuree:wght@300&family=Josefin+Sans&family=Nunito+Sans:wght@300&family=Source+Sans+Pro:wght@300&display=swap" rel="stylesheet">
</head>
<body>
    {% block 'body'%}
    {% endblock%}
</body>
</html>